combined with everythin on latest layout and global themes, working scroll and bringing data from mock json server for upcoming cards
robert-szalkai/meeting-rooms-booking pull request #22
Opened 2023-04-13 15:36 UTC by Liubzzz

2023-04-13 16:04 UTC, cristiberzescu commented on src/components/TabletApp/LeftSide/LeftSide.tsx
> +                            color: "white",
same here

2023-04-18 08:44 UTC, alexgaita requested changes

2023-04-18 08:44 UTC, alexgaita commented on src/api/getRequests.ts
> +const getMeetingsData= async()=>{
Missed a space here
```suggestion
const getMeetingsData = async()=>{
```

2023-04-18 08:44 UTC, alexgaita commented on src/components/TabletApp/LeftSide/LeftSide.tsx
> +        | {
Create a new type for this meeting like Meeting where you specify the fields, don't inline them here

2023-04-18 08:44 UTC, alexgaita commented on src/components/TabletApp/LeftSide/LeftSide.tsx
>      let currDate = new Date();
use dayjs for dates

2023-04-18 17:58 UTC, CatalinTiu requested changes
Check the file differences that must be resolved also! Everything else looks great!

2023-04-20 05:39 UTC, CatalinTiu approved these changes
Looks good to me

2023-04-24 06:43 UTC, CatalinTiu approved these changes

2023-04-24 06:43 UTC, CatalinTiu commented on src/components/TabletApp/RightSide/MeetingInfo/MeetingInfo.tsx
>      };
Maybe use the getMeetingByID function from getRequests file or create it there and import it here

2023-04-24 13:52 UTC, merged