Finished Advanced Book Form
robert-szalkai/meeting-rooms-booking pull request #35
Opened 2023-04-24 06:25 UTC by AlexandruFercal01

2023-04-24 06:36 UTC, CatalinTiu commented on src/components/TabletApp/RightSide/AdvancedBook/Participants.tsx
> +                        console.log(result);
Remove console.log() when you're finished testing them

2023-04-24 06:39 UTC, CatalinTiu commented on src/components/TabletApp/RightSide/AdvancedBook/DateSelector.tsx
> +};
Use the getMeetings from the getRequests file instead of decalring it again here, I see you commented the import above

2023-04-24 09:35 UTC, cristiberzescu commented on src/components/TabletApp/RightSide/AdvancedBook/DateSelector.tsx
> +
delete the comments

2023-04-24 09:37 UTC, cristiberzescu approved these changes
looks good

2023-04-25 11:32 UTC, robert-szalkai requested changes

2023-04-25 12:15 UTC, Liubzzz approved these changes

2023-04-25 12:15 UTC, Liubzzz commented on src/components/TabletApp/RightSide/AdvancedBook/DateSelector.tsx
> -                    InputProps={{ disableUnderline: true }}
delete parts of unused code

2023-04-26 10:58 UTC, robert-szalkai requested changes

2023-04-26 10:58 UTC, robert-szalkai commented on src/components/TabletApp/RightSide/AdvancedBook/AdvancedBook.tsx
> +    meeting_description: string;
keep camel case for defining names

2023-04-26 10:59 UTC, robert-szalkai approved these changes

2023-04-26 11:34 UTC, merged