Charts + Hub
robert-szalkai/meeting-rooms-booking pull request #46
Opened 2023-04-26 16:26 UTC by thedeath154

Almost done, all that is left is the proper json and convert from scrollable charts to all on the same page

2023-04-27 08:16 UTC, daniel-mita requested changes

2023-04-27 08:16 UTC, daniel-mita commented on tsconfig.json
> -    "strict": true,                                      /* Enable all strict type-checking options. */
Don't remove this, if there is a typescript error you need to solve it, not remove the strict type checking

2023-04-27 08:17 UTC, daniel-mita commented on yarn.lock
Why do you have both yarn.lock and package-lock? Decide on using either yarn or npm and remove the other

2023-04-27 08:48 UTC, robert-szalkai requested changes

2023-04-27 08:48 UTC, robert-szalkai commented on src/components/Charts/Chart.tsx
> +                <IconButton component={Link} to="http://localhost:3000/hub">
you should NOT use absolute paths. Use relative paths `to="/hub"`

2023-04-27 08:48 UTC, robert-szalkai commented on src/components/Charts/Chart.tsx
> +                <IconButton component={Link} to="http://localhost:3000/hub">
same here

2023-04-27 08:48 UTC, robert-szalkai commented on src/components/Hub/Hub.tsx
> +            <a href="http://localhost:3000/selection">
same here

2023-04-28 10:24 UTC, Liubzzz commented on meetingRoomData.json
> -
unnecessary spaces

2023-04-28 10:24 UTC, Liubzzz commented on meetingRoomData.json
> -
same here

2023-04-28 10:24 UTC, Liubzzz commented on src/components/Charts/Chart.tsx
> +                            fill="#8884d8"
use constants here, for filling colors in charts

2023-05-01 16:51 UTC, closed without merging