Login page, protected routes, log out modals
robert-szalkai/meeting-rooms-booking pull request #56
Opened 2023-05-02 10:45 UTC by AlexandruFercal01

2023-05-02 10:53 UTC, CatalinTiu requested changes

2023-05-02 10:53 UTC, CatalinTiu commented on src/components/LoginPage/LoginForm.tsx
> +    const getUserss = async () => {
Maybe rename getUserss to something less vague

2023-05-02 10:53 UTC, CatalinTiu commented on src/components/Admin/LogOutModal/LogOutModal.tsx
> +type ConfirmationModalProps = {
Change Type to Interface

2023-05-02 11:01 UTC, CatalinTiu approved these changes

2023-05-11 07:59 UTC, daniel-mita requested changes

2023-05-11 07:59 UTC, daniel-mita commented on src/api/users.ts
> +const getUser = async (
This can be easily mistaken with getUsers, rename this to getSingleUser

2023-05-11 07:59 UTC, daniel-mita commented on src/components/Admin/Admin.tsx
> +                    handleClose(setShowLogoutModal);
Why pass the setter function here as an argument when you already have access to it in the function scope?

2023-05-11 07:59 UTC, daniel-mita commented on src/components/Admin/LogOutModal/LogOutModal.tsx
> +                        //alignItems: "left",
Delete this comment if it's not relevant

2023-05-11 07:59 UTC, daniel-mita commented on src/components/LoginPage/LoginForm.tsx
> +        console.log(users);
Remove this console.log

2023-05-11 07:59 UTC, daniel-mita commented on src/components/LoginPage/LoginForm.tsx
> +    }, []);
Every time the component rerenders this block of code will run, are you sure you want this behaviour?

2023-05-11 07:59 UTC, daniel-mita commented on src/interfaces/interfaces.ts
> +export interface userInfo{
interfaces start with capital letter

2023-05-11 07:59 UTC, daniel-mita commented on src/components/TabletApp/LogOutModal.tsx
> +                                navigate("/login");
If you only navigate to the login screen, the user will still be logged in, extract this in a sepparate function and handle all the effects of the logout like deleting tokens and whatever from the local storage.

2023-05-16 08:28 UTC, robert-szalkai approved these changes

2023-05-16 08:28 UTC, merged